### PR TITLE
Apple

### PR DESCRIPTION
**Pull request by tiagoit**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
### Pull Request under the review by X BY ADDO

**Review by Forison — APPROVED** [review]
### Good Job Tiago 👏 👏 👏 
You have done a great job here 👌. Your file organization looks awesome 👌
proceed to the next project  💪 💪 💪 
HAPPY CODING🙃

> Friendly reminder: You should use Github/Git Flow in this project. However, changing it now would take too much time.
Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.

**Comment by tiagoit** [comment]
Thank you @Forison.

**Comment by tiagoit** [comment]
> ### Good Job Tiago   
> You have done a great job here . Your file organization looks awesome 
> proceed to the next project   
> HAPPY CODING
> 
> > Friendly reminder: You should use Github/Git Flow in this project. However, changing it now would take too much time.
> > Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.

@Forison About the Git Flow, I've created a feature branch and PR into master, what did I miss?

**Comment by Forison** [comment]
It was ok, I just wanted to tell you to comment on every pull request you make it is not too serious but important as a professional developer.

**Comment by tiagoit** [comment]
> It was ok, I just wanted to tell you to comment on every pull request you make it is not too serious but important as a professional developer.

Okay, I will do it, thanks for the feedback.

**Pull request merged**
